### ISSUE TITLE
Snakes do not evert!

### ISSUE THREAD

**Issue by BlackCapCoder** [olaven/sunday-funday#1]
If you press the arrow key that is opposite to the direction that your snake is crawling, your snake will eat itself. I don't know if you've ever seen a snake, but I'll have you know that unlike socks it is anatomically impossible for snakes to fold in over themselves. I drew you this diagram to illustrate this:

![](https://i.imgur.com/0jzFIo4.png)

**Comment by olaven** [comment]
Added a quick fix. To be improved at a later point 😄
